version: "3.3"
services:
  bigtable-emulator:
    image: "google/cloud-sdk"
    command: "gcloud beta emulators bigtable start --host-port=0.0.0.0:8086"
    ports:
    - "8086:8086"
  dev-0:
    image: "$BASIC_RUNNER_IMAGE_NAME"
    volumes:
    - "$PWD/app/target:/mnt/app/target"
    ports:
    - "8430:8430"
    - "8440:8440"
    # - "8480:80" TODO Vite
    environment:
    - "BIGTABLE_EMULATOR_HOST=bigtable-emulator:8086"
  dev-bootstrap:
    image: "$BASIC_RUNNER_IMAGE_NAME"
    volumes:
    - "$PWD/app/target:/mnt/app/target"
    - "$FS_EVENT_STORE_DIR:/mnt/event-store"
    ports:
    - "8429:8430"
