name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      # - name: mvn dependency:analyze
      #   run: mvn dependency:analyze -DfailOnWarning=true
      - name: Maven
        run: mvn --batch-mode --update-snapshots verify org.jacoco:jacoco-maven-plugin:report-aggregate
      - uses: cicirello/jacoco-badge-generator@v2
        id: jacoco-badge-generator
        with:
          jacoco-csv-file: target/site/jacoco-aggregate/jacoco.csv
          generate-coverage-badge: false
          generate-branches-badge: true
          branches-label: "branch coverage"
      - name: Post jacoco-badge-generator
        run: |
          echo "coverage = ${{ steps.jacoco-badge-generator.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco-badge-generator.outputs.branches }}"
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Monalisa Octocat'
            git config --global user.email '84229+ulzha@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi
