name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '19'
          distribution: 'temurin'
      # - name: mvn dependency:analyze
      #   run: mvn dependency:analyze -DfailOnWarning=true

      - name: Code style
        run: |
          flags="--batch-mode"
          checks="com.spotify.fmt:fmt-maven-plugin:check"
          mvn $flags $checks
          mvn $flags $checks -f example/clicc-tracc
          mvn $flags $checks -f example/copy

      - name: Maven verify
        run: |
          flags="--batch-mode -Dfmt.skip=true -Pjacoco"
          checks="verify"
          mvn $flags $checks
          mvn $flags $checks -f example/clicc-tracc
          mvn $flags $checks -f example/copy

      - uses: cicirello/jacoco-badge-generator@v2
        id: jacoco-badge-generator
        with:
          # TODO examples too (even though they have separate lifecycle, conceptually)
          jacoco-csv-file: ./tools/coverage/target/site/jacoco-aggregate/jacoco.csv
          generate-coverage-badge: false
          generate-branches-badge: true

      - name: Post jacoco-badge-generator
        run: |
          echo "coverage = ${{ steps.jacoco-badge-generator.outputs.coverage }}"
          echo "branch coverage = ${{ steps.jacoco-badge-generator.outputs.branches }}"
          if [[ `git status --porcelain` ]]; then
            git config --global user.name 'Monalisa Octocat'
            git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
            git add -A
            git commit -m "Autogenerated JaCoCo coverage badge"
            git push
          fi
