name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '19'
          distribution: 'temurin'
      # - name: mvn dependency:analyze
      #   run: mvn dependency:analyze -DfailOnWarning=true

      - name: Code style
        run: |
          flags="--batch-mode"
          checks="com.spotify.fmt:fmt-maven-plugin:check"
          mvn $flags $checks
          mvn $flags $checks -f example/clicc-tracc
          mvn $flags $checks -f example/copy

      - name: Maven
        run: |
          flags="--batch-mode -Dfmt.skip=true -Pjacoco"
          mvn $flags install
          mvn $flags verify -f example/clicc-tracc
          mvn $flags verify -f example/copy

      - uses: cicirello/jacoco-badge-generator@v2
        id: jacoco-badge-generator
        with:
          # TODO examples too (even though they have separate lifecycle, conceptually)
          jacoco-csv-file: ./tools/coverage/target/site/jacoco-aggregate/jacoco.csv
          generate-coverage-badge: false
          generate-branches-badge: true

      - name: Publish coverage
        run: .github/workflows/publish-coverage-to-pages.sh
